### ISSUE TITLE
Tags Are Not SPM-Compliant

### ISSUE THREAD

**Issue by Frizlab** [zoul/generic-json-swift#23]
I’m trying to use your project in one of my SPM-based project, but your tags are not SPM-compliant. Tags should be directly the version number, with no suffix nor prefix.

Would you be so kind as to fix that?
Thanks

**Comment by zoul** [comment]
Thank you! Will fix as soon as possible.

**Comment by zoul** [comment]
This took a bit longer than I thought, sorry. Does it work now?

**Comment by Frizlab** [comment]
Yes, it does. Thanks!
