### ISSUE TITLE
Improve querying using dynamic member lookup?

### ISSUE THREAD

**Issue by zoul** [zoul/generic-json-swift#5]
Could we use [dynamic member lookup](https://github.com/apple/swift-evolution/blob/master/proposals/0195-dynamic-member-lookup.md) to improve the syntax of ad-hoc queries?

**Comment by cjmconie** [comment]
Very interesting proposal. From the author's notes it appears to be directly applicable to this use case. Querying/traversing the JSON tree should become much clearer and more concise.

I will try and look into this as soon as time allows.
